---
name: Continuous Deployment

on:
  push:
    branches:
      - master
      - production
      - main
  pull_request: []

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Run Test
        run: npm test
